### ISSUE TITLE
Link under Max’s name in README is broken

### ISSUE THREAD

**Issue by ulysses4ever** [danielsmax/cs7805-final-presentation#1]

**Comment by ulysses4ever** [comment]
It's sometimes beneficial to reference the number of issue from the closing commit message, so that the issue and the commit get interlinked and the issue closes automagically. The other way to achieve this interlink is to reference the commit from here when closing the issue. 

So, closed with fe782db.

**Comment by mdnls** [comment]
good advice! thanks

**Comment by ulysses4ever** [comment]
Very welcome!
